/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author HP-PC
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
    }

    private void displayPanel(JPanel panel){
        displayPanel.removeAll();
        displayPanel.repaint();
        displayPanel.revalidate();
        
        displayPanel.add(panel);
        displayPanel.repaint();
        displayPanel.revalidate();
    }
    
    private void changeColors(JLabel label) {
        JLabel[] labels = {pembelianLabel, penjualanLabel, produkLabel, kategoriLabel,userLabel};
        for (JLabel labeli : labels) {
            if (labeli.equals(label)) {
                labeli.setBackground((Color) displayPanel.getBackground());
            } else {
                labeli.setBackground((Color) panelMenu.getBackground());
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        dashboardLabel = new javax.swing.JLabel();
        pembelianLabel = new javax.swing.JLabel();
        penjualanLabel = new javax.swing.JLabel();
        produkLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        kategoriLabel = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Toko");
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        panelMenu.setBackground(new java.awt.Color(102, 102, 102));
        panelMenu.setForeground(new java.awt.Color(255, 255, 255));
        panelMenu.setMaximumSize(new java.awt.Dimension(400, 700));
        panelMenu.setMinimumSize(new java.awt.Dimension(400, 700));
        panelMenu.setPreferredSize(new java.awt.Dimension(400, 700));

        dashboardLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dashboardLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardLabel.setText("DASHBOARD");

        pembelianLabel.setBackground(new java.awt.Color(102, 102, 102));
        pembelianLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        pembelianLabel.setForeground(new java.awt.Color(255, 255, 255));
        pembelianLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pembelianLabel.setText("Pembelian");
        pembelianLabel.setOpaque(true);
        pembelianLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pembelianLabelMouseClicked(evt);
            }
        });

        penjualanLabel.setBackground(new java.awt.Color(102, 102, 102));
        penjualanLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        penjualanLabel.setForeground(new java.awt.Color(255, 255, 255));
        penjualanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        penjualanLabel.setText("Penjualan");
        penjualanLabel.setMaximumSize(new java.awt.Dimension(148, 41));
        penjualanLabel.setMinimumSize(new java.awt.Dimension(148, 41));
        penjualanLabel.setOpaque(true);
        penjualanLabel.setPreferredSize(new java.awt.Dimension(148, 41));
        penjualanLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penjualanLabelMouseClicked(evt);
            }
        });

        produkLabel.setBackground(new java.awt.Color(102, 102, 102));
        produkLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        produkLabel.setForeground(new java.awt.Color(255, 255, 255));
        produkLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        produkLabel.setText("Produk");
        produkLabel.setMaximumSize(new java.awt.Dimension(148, 41));
        produkLabel.setMinimumSize(new java.awt.Dimension(148, 41));
        produkLabel.setOpaque(true);
        produkLabel.setPreferredSize(new java.awt.Dimension(148, 41));
        produkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produkLabelMouseClicked(evt);
            }
        });

        userLabel.setBackground(new java.awt.Color(102, 102, 102));
        userLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText("User");
        userLabel.setOpaque(true);
        userLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLabelMouseClicked(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-logout-50.png"))); // NOI18N

        kategoriLabel.setBackground(new java.awt.Color(102, 102, 102));
        kategoriLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        kategoriLabel.setForeground(new java.awt.Color(255, 255, 255));
        kategoriLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kategoriLabel.setText("Kategori");
        kategoriLabel.setOpaque(true);
        kategoriLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kategoriLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pembelianLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(penjualanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(produkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(dashboardLabel))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(logout)))
                .addContainerGap(87, Short.MAX_VALUE))
            .addComponent(kategoriLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(dashboardLabel)
                .addGap(42, 42, 42)
                .addComponent(pembelianLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penjualanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(produkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kategoriLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(16, 16, 16))
        );

        displayPanel.setBackground(new java.awt.Color(204, 204, 204));
        displayPanel.setMaximumSize(new java.awt.Dimension(800, 700));
        displayPanel.setMinimumSize(new java.awt.Dimension(800, 700));
        displayPanel.setPreferredSize(new java.awt.Dimension(800, 700));
        displayPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pembelianLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembelianLabelMouseClicked
        displayPanel(new Pembelian());
        changeColors(pembelianLabel);
    }//GEN-LAST:event_pembelianLabelMouseClicked

    private void penjualanLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penjualanLabelMouseClicked
        displayPanel(new Penjualan());
        changeColors(penjualanLabel);
    }//GEN-LAST:event_penjualanLabelMouseClicked

    private void produkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produkLabelMouseClicked
        displayPanel(new Produk());
        changeColors(produkLabel);
    }//GEN-LAST:event_produkLabelMouseClicked

    private void userLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLabelMouseClicked
        displayPanel(new User());
        changeColors(userLabel);
    }//GEN-LAST:event_userLabelMouseClicked

    private void kategoriLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kategoriLabelMouseClicked
        displayPanel(new Kategori());
        changeColors(kategoriLabel);
    }//GEN-LAST:event_kategoriLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel kategoriLabel;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JLabel pembelianLabel;
    private javax.swing.JLabel penjualanLabel;
    private javax.swing.JLabel produkLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
